### ISSUE TITLE
Problems on running php bin/adminconsole sulu:build dev

### ISSUE THREAD

**Issue by ghost** [sulu/sulu-minimal#77]
Step 1: `Running php bin/adminconsole sulu:build dev` on a fresh sulu-minimal installation

Getting two errors:

[WARNING] Some commands could not be registered:                                                                                                                                             
The command defined in "Sulu\Bundle\PreviewBundle\Command\CacheClearCommand" cannot have an empty name.  

and

In adminDevDebugProjectContainer.php line 1940:                                                                                                                                                                 
Compile Error: ContainerYswzosq\adminDevDebugProjectContainer::load(): Failed opening required ''/var/cache/admin/dev/ContainerYswzosq/getDoctrine_SchemaUpdateCommandService.php' (include_path='.:/usr/share/php') 

Any ideas?

**Comment by danrot** [comment]
@Nitaco These are problems that have occured because of the new Symfony 3.4 release (they have some breaking changes there). That should be fixed with #3664, which has already been released in the [latest hotfix](https://github.com/sulu/sulu/releases/tag/1.6.9). Just update to this version, and make sure you've deleted the Symfony cache, and you should be fine 😃
